# Generated by Django 5.1.6 on 2025-03-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoProject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animatoroffer',
            name='available_date',
        ),
        migrations.AddField(
            model_name='animatoroffer',
            name='available_dates',
            field=models.TextField(default='[]', help_text='Список доступных дат в формате JSON (например, ["2025-03-10", "2025-03-11"])'),
        ),
        migrations.AddField(
            model_name='animatoroffer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='animators/'),
        ),
    ]
